#!/usr/bin/env bash
docker_exec=nichijou
cmd="jupyter notebook --notebook-dir=/home/lizytalk/ --ip=0.0.0.0"
params='--name lzy-jupyter -p 8888:8888 --ipc host -d --restart always'
${docker_exec} "${cmd}" "${params}"
