#!/usr/bin/env bash
cmd=${1}
extra_params=${@:2}
docker_exec=nvidia-docker
user=
tag=lizytalk/nichijou:cp38_gpu
echo cmd: ${cmd}
echo extra params: ${extra_params}
cmd="sudo ${docker_exec} run -it --user $(id -u) ${extra_params} -v /home/${user}:/home/${user} -e USERNAME=${user} ${tag} ${cmd}"
echo ${cmd}
${cmd}
